// Generated by https://quicktype.io

export interface Status {
    buildNumber: string;
    enabledFeatures: string[];
    idpUrl: string;
    trackingId: string;
    fileHandlers: FileHandlers;
}

export interface FileHandlers {
    FileService: FileService;
    Local: FileService;
}

export interface FileService {
    apiUrl: string;
    features: string[];
}
