// Generated by https://quicktype.io

export interface SubjectAverage {
    Tantargy: Tantargy;
    Atlag: number | null;
    Uid: string;
    SortIndex: number;
    AtlagAlakulasaIdoFuggvenyeben: AtlagDatumErtek[];
}

export interface AtlagDatumErtek {
    Atlag: number;
    Datum: string;
}

export interface Tantargy {
    Uid: string;
    Kategoria: Kategoria;
    Nev: string;
}

export interface Kategoria {
    Uid: string;
    Leiras: string;
    Nev: string;
}
